### ISSUE TITLE
MineCLIP release

### ISSUE THREAD

**Issue by bnstuycn** [MineDojo/MineDojo#1]
Will MineCLIP code and pretrained models be released sometime?

**Comment by LinxiFan** [comment]
Hi! Thanks for your interest in our work. We do not have a timeline for MineCLIP yet, but will let you know when things change!

**Comment by Matheus-Garbelini** [comment]
@LinxiFan Hi, is there any updates on this?
Is the pretrained model too big to be shared (> 20GB) or the runtime requirements are too high for general use with an RTX2060/3060, etc?

Regards.

**Comment by KoolenDasheppi** [comment]
I hope that MineCLIP does get released sooner than later, as it seems like such an interesting piece of AI. Looking forward to the release!

**Comment by LinxiFan** [comment]
Dear all, we have just open-sourced the code for MineCLIP, MineAgent, and the scripted reward functions used in the paper! https://github.com/MineDojo/MineCLIP. The pretrained weights are still TBD due to some procedure issues, but please stay tuned! Thank you all so much for your interest and patience!
