### ISSUE TITLE
Iterating over dataset takes too long!

### ISSUE THREAD

**Issue by shirinssalehi** [MineDojo/MineDojo#10]
Hello,

I am trying to extract the text and images from the reddit dataset, but iterating over the data is taking too much time. Is there any reason for that? Do you recommend any way I can extract the data more rapidly?

Thanks!

**Comment by shirinssalehi** [comment]
Hi @wangguanzhi. Thank you for your response. How can I use Pushshift with the MineDojo API for getting the Reddit dataset that is collected in MineDojo?

**Comment by wangguanzhi** [comment]
Hi, our MineDojo API does not support Pushshift since it is not an official Reddit API. You would have to download the data using Pushshift externally. Here is the [link](https://github.com/pushshift/api) to their GitHub. For ease of use, you can also check out the [Pushshift API Wrapper](https://psaw.readthedocs.io/en/latest/).

**Comment by yunfanjiang** [comment]
Close the question now. Feel free to comment/reopen when having new questions!
