### ISSUE TITLE
Error When Running pip install -e .

### ISSUE THREAD

**Issue by Snowplou** [MineDojo/MineDojo#12]
When I run `pip install -e .`, it gives me this error:

(minedojo) C:\Users\john\Documents\VSC\MineDojo\MineDojo>pip install -e .
Obtaining file:///C:/Users/john/Documents/VSC/MineDojo/MineDojo
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\john\Documents\VSC\MineDojo\MineDojo\setup.py", line 38, in <module>
          long_description=_read_file("README.md"),
        File "C:\Users\john\Documents\VSC\MineDojo\MineDojo\setup.py", line 16, in _read_file
          return fp.read()
        File "C:\Users\john\anaconda3\envs\minedojo\lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 14717: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

What should I do to fix this?

**Comment by AmsterPlays** [comment]
I fixed this issue by deleting **line 38** in **setup.py** entirely, seems to fix the error, not sure if it breaks anything else in the long run though.

**Comment by JigglyJoogins** [comment]
Have you already run `git install minedojo`?

**Comment by yunfanjiang** [comment]
hey @Snowplou, thank you for reporting this issue. Please note that we've only tested on Ubuntu 20.04 and MacOS (intel chip). It may not work on other platforms. Note that we have recently released an [official docker image](http://docs.minedojo.org/sections/getting_started/install.html#docker-image). We'd recommend to use the docker image if on Windows machines.
Regarding @AmsterPlays 's workaround, it doesn't affect anything because L38 just sets a long description of the package.

Please let me know if you encounter other problems!

**Comment by Snowplou** [comment]
> I fixed this issue by deleting **line 38** in **setup.py** entirely, seems to fix the error, not sure if it breaks anything else in the long run though.

I just tried this and it fixed the problem. Thank you!
