### ISSUE TITLE
Multi agent worlds

### ISSUE THREAD

**Issue by TheRealAakash** [MineDojo/MineDojo#15]
Is it possible for an agent to join an existing server to run in a multi agent capacity?

**Comment by yunfanjiang** [comment]
Hi, thanks for asking! Please note that we don't officially support this feature. However, because our simulator builds upon MineRL v0.4, there are some relevant online discussions such as [this](https://github.com/minerllabs/minerl/issues/615). Feel free to let me know if you have other questions. Thank you for your interest again.
