### ISSUE TITLE
Running Env offline or a self-contained docker image

### ISSUE THREAD

**Issue by siriusctrl** [MineDojo/MineDojo#16]
Hi there, thanks for the fantastic work. I noticed that the Docker Image has recently been released. However, the environment is still not able to run in an offline fashion, as it seems like the env is trying to download something from the Gradle. Is that possible to have a fully self-contained image in the future?

**Comment by yunfanjiang** [comment]
Hey @siriusctrl , thanks for trying out our docker! Please note that the image is self-contained in the sense that we ship all dependencies such as JDK and features like GPU-accelerated simulation. Due to the modding framework that MineDojo uses, it may pull new assets on-the-fly. We highlighted this fact in our [doc](http://docs.minedojo.org/sections/getting_started/sim.html#) as well. There are also some relevant online discussions from MineRL v0.4 such as [this](https://github.com/minerllabs/minerl/issues/412). 

Please note that because this behavior roots in the modding framework, we are very unlikely to fix it in the near future. Apologize for that. Feel free to let me know if you have any other questions.
