### ISSUE TITLE
[documentation] Is there a reccomended X Server for headless users?

### ISSUE THREAD

**Issue by Sanokei** [MineDojo/MineDojo#22]
Wanna know if one of the people working on this project used one and favors it over another.

**Comment by johnpaulbin** [comment]
I use XLaunch ([VcXsrv](https://sourceforge.net/projects/vcxsrv/)) for windows 10 and it works great

**Comment by Sanokei** [comment]
Also, if anybody is curious, this is how I got the project working on windows 10 build 2000 or newer with WSL.

inside windows 

run `wsl --install -d ubuntu` in a command prompt

inside linux

install python 3.9
`sudo apt install software-properties-common`
`sudo add-apt-repository ppa:deadsnakes/ppa`
`sudo apt install python3.9`
add python 3.9 to python
`sudo update-alternatives --install /usr/bin/python python /usr/bin/python3.9 10`
`sudo update-alternatives --install /usr/bin/python python /usr/bin/python3.8 1`
`sudo apt-get update`
Make python 3.9 the default and install pip
`sudo update-alternatives --config python`
`sudo apt install python3-pip`
check that it it insalled pip for python 3.9 and not 3.8 with `pip --version`

### Need to fix these issues before they come up:
Fix the [`ModuleNotFoundError: No module named 'apt_pkg`](https://stackoverflow.com/questions/56218562/how-to-fix-modulenotfounderror-no-module-named-apt-pkg) error
`sudo vim /usr/bin/add-apt-repository`
edit line 1 `#!/usr/bin/python3` to `#!/usr/bin/python3.8`

Fix the [`Package ‘vnc4server’ has no installation candidate.`](https://www.dev2qa.com/how-to-fix-e-package-vnc4server-has-no-installation-candidate/) error
`sudo vim /etc/apt/sources.list`
add `deb http://cn.archive.ubuntu.com/ubuntu/ bionic universe` to the bottom
`sudo apt-get update` 
`sudo apt-get install vnc4server`

Then follow prerequisites from [website](https://docs.minedojo.org/sections/getting_started/install.html)

**Comment by yunfanjiang** [comment]
Hey @Sanokei , thank you so much for your detailed instruction to make it work on Windows. We will add these instructions to our doc at some point.

**Comment by AkagawaTsurunaki** [comment]
When I executed command `sudo apt-get install vnc4server`, I got
```
Package vnc4server is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or is only available from another source

E: Package 'vnc4server' has no installation candidate
```
I found the solution at [here](https://askubuntu.com/questions/1505944/package-vnc4server-has-no-installation-candidate`) since   `vnc4server` is no longer used.
Using `sudo apt-get install tigervnc-standalone-server` helps me solve this problem.

**Comment by AkagawaTsurunaki** [comment]
When I executed command `sudo apt-get install vnc4server`, I got
```
Package vnc4server is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or is only available from another source

E: Package 'vnc4server' has no installation candidate
```
I found the solution at [here](https://askubuntu.com/questions/1505944/package-vnc4server-has-no-installation-candidate`) since   `vnc4server` is no longer used and it was replaced by `tigervnc-standalone-server`.

**Using `sudo apt-get install tigervnc-standalone-server` helps me solve this problem.**
